CREATE TABLE
    CLIENTE (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    PRODUTO(
        ID INT AUTO_INCREMENT,
        DESCRICAO VARCHAR(100) NOT NULL,
        PRECO_UNITARIO NUMERIC(20, 2),
        PRIMARY KEY (ID)
    );

CREATE TABLE
    PEDIDO(
        ID INT AUTO_INCREMENT,
        CLIENTE_ID INT REFERENCES CLIENTE(ID),
        DATA DATE,
        VALOR_TOTAL NUMERIC(20, 2),
        PRIMARY KEY (ID)
    );

CREATE TABLE
    ITEM_PEDIDO(
        ID INT AUTO_INCREMENT,
        PEDIDO_ID INT REFERENCES PEDIDO(ID),
        PRODUTO_ID INT REFERENCES PRODUTO(ID),
        QUANTIDADE INT,
        VALOR NUMERIC(20, 2),
        PRIMARY KEY (ID)
    );